version: 2.1

orbs:
  python: circleci/python@1.4.0

jobs:

  build-and-test-dev:
    executor: python/default
    steps:
      - checkout
      # pip require package
      - run:
          command: pip install --user -r dev_requirements.txt
          name: pip requirements.txt
      # unit test start
      - run:
          command: python ./test/unit_test/user_test/fast_http_user_test.py
          name: user_test
      - run:
          command: python ./test/unit_test/user_test/http_user_test.py
          name: http user test
      - run:
          command: python ./test/unit_test/callback_test/callback_test.py
          name: callback_test

  build-and-test-stable:
    executor: python/default
    steps:
      - checkout
      # pip require package
      - run:
          command: pip install --user -r requirements.txt
          name: pip requirements.txt
      # unit test start
      - run:
          command: python ./test/unit_test/user_test/fast_http_user_test.py
          name: fast http user test
      - run:
          command: python ./test/unit_test/user_test/http_user_test.py
          name: callback_test

workflows:
  main:
    jobs:
      - build-and-test-dev
      - build-and-test-stable:
          requires:
            - build-and-test-dev
